server:
    port: 8080
    error:
        include-message: always

spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        url: jdbc:mysql://localhost:3306/urlshortener_db
        password: olakay@pyDev1
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
        open-in-view: true


logging:
  level:
    org:
      springframework:
        security: DEBUG

  